#!/usr/bin/env python
#
# Usage: vwine-setup-XXXX <NEW_VIRT_ENV>
#
# Setup a fresh virtual-wine and install Python into.
# Installation is doen by $WINREPO"/XXX/install.bat
#

WINREPO = '~/devel/windows-repos'

import os
import sys
import argparse
import subprocess

def call(cmdargs):
    return subprocess.Popen(cmdargs, stdout=subprocess.PIPE).communicate()[0]


WINREPO = os.path.expanduser(WINREPO)

# extract setup/config to e used from basename of script
setup = os.path.basename(sys.argv[0])[len("vwine-setup-"):]
if not setup:
    raise SystemExit("Basename does not contain setup-name")

# get the name of the environment from the install.bat file
installscript = os.path.join(WINREPO, setup, 'install.bat')
if not os.path.exists(installscript):
    raise SystemExit("Installscript %r not found" % installscript)
try:
    envname = open(installscript, 'rU').read().split()
    envname = envname[envname.index('ENVNAME')+1]
except (IndexError, ValueError):
    raise SystemExit("Installscript %r is missing ENVNAME setting"
                     % installscript)
except IOError, e:
    raise SystemExit(e)

# wineprefix is the place where the new virtal-wine setup is created
wineprefix = os.path.join(WINREPO, envname)

parser = argparse.ArgumentParser()
parser.add_argument('-c', '--clean', action='store_true')
parser.add_argument('-f', '--force', action='store_true')
args = parser.parse_args() 

# created the virtal-wine environment
cmd = ['vwine-setup']
if args.clean: cmd.append('--clean')
if args.force: cmd.append('--force')
cmd.append(wineprefix)
rc = subprocess.call(cmd)
if rc:
    raise SystemExit(rc)

# install the softwae into the virtal-wine environment
installscript = call(['winepath', '-w', installscript]).strip()
rc = subprocess.call(['wineconsole', installscript])
if rc:
    raise SystemExit(rc)
